### PR TITLE
Add some more hints

### PR DESCRIPTION
**Pull request by Gobot1234**

### CODE REVIEW

**Comment by ThatXliner** [comment]
Thanks for contributing! I haven't published this repo to PyPi yet mainly because I'm still experimenting with it.

The thing is, I've noticed you are using 3.9's `|` operator for types and `Literal` for 3.8. I'm not sure if it matters too much, please tell me.

If it doesn't, I'll happily merge this (possibly even publish the first release)

**Comment by Gobot1234** [comment]
Yeah you can use all the new syntax/types inside of .pyi files even if your on 3.6.

**Comment by Gobot1234** [comment]
Yeah you can use all the new syntax/types inside of .pyi files even if your on 3.6.

**Comment by ThatXliner** [comment]
Ok, looks good!

**Pull request merged**
